
title: Ye Shen
description: PhD Candidate • Health Policy (Decision Sciences) • Harvard University
baseurl: "/yeshen-site" 
url: "https://yshen11.github.io"
theme: null
markdown: kramdown
permalink: pretty

nav:
  - name: Home
    url: "/"
  - name: CV
    url: "/cv/"
  - name: Contact
    url: "/contact/"
  
social:
  scholar: "https://scholar.google.com/citations?user=c3IRn-EAAAAJ"
  linkedin: "https://www.linkedin.com/in/yeshen11"

exclude:
  - README.md
  - LICENSE
