
title: Ye Shen
description: PhD Candidate • Health Policy (Decision Sciences) • Harvard University
baseurl: "/yeshen-site" 
url: "https://yshen11.github.io"
theme: null
markdown: kramdown
permalink: pretty

nav:
  - name: Home
    link: /
  - name: CV
    link: /cv.md
  - name: Contact
    link: /contact.md
  
social:
  scholar: "https://scholar.google.com/citations?user=c3IRn-EAAAAJ"
  linkedin: "https://www.linkedin.com/in/yeshen11"

exclude:
  - README.md
  - LICENSE
