
title: Ye Shen
description: PhD Candidate • Health Policy (Decision Sciences) • Harvard University
baseurl: "/yeshen-site" 
url: "https://yshen11.github.io"
theme: null
markdown: kramdown
permalink: pretty

nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Research
    link: /research/
  - name: Publications
    link: /publications/
  - name: Teaching
    link: /teaching/
  - name: CV
    link: /cv/
  - name: Contact
    link: /contact/
    link: /
  - name: About
    link: /about/
  - name: Research
    link: /research/
  - name: Publications
    link: /publications/
  - name: Teaching
    link: /teaching/
  - name: CV
    link: /cv/
  - name: Contact
    link: /contact/

social:
  scholar: "https://scholar.google.com/citations?user=c3IRn-EAAAAJ"
  linkedin: "https://www.linkedin.com/in/yeshen11"
  twitter: "https://x.com/yeah_shen"

exclude:
  - README.md
  - LICENSE
